export const ANALYTICS_OPTIONS = [
  { id: 'intrusion', label: 'Intrusão' },
  { id: 'evasion', label: 'Abandono de função (evasão de posto)' },
  { id: 'agglomeration', label: 'Aglomeração' },
  { id: 'permanence', label: 'Permanência' },
  { id: 'inactivity', label: 'Inatividade (dormindo ou celular)' },
  { id: 'vehicle_intrusion', label: 'Detecção de veículo' },
  { id: 'vehicle_agglomeration', label: 'Congestionamento de veículos' },
  { id: 'vehicle_evasion', label: 'Ausência de veículo' },
  { id: 'animal_intrusion', label: 'Detecção de PET' },
  { id: 'panic', label: 'Pânico facial' },
  { id: 'lpr', label: 'LPR - placa de veículos' },
  { id: 'radar', label: 'Radar de velocidade' },
  { id: 'epi_intrusion', label: 'Detecção de EPI' },
  { id: 'epi_evasion', label: 'Ausência de EPI' },
  { id: 'scene_change', label: 'Mudança de cena' },
  { id: 'time_lapse', label: 'Timelapse' },
  { id: 'inactive_camera', label: 'Câmera inativa' },
];