export const ANALYTICS_OPTIONS = [
  { id: 'intrusion', label: 'Intrusão' },
  { id: 'evasion', label: 'Abandono de função (evasão de posto)' },
  { id: 'aglommeration', label: 'Aglomeração' },
  { id: 'permanence', label: 'Permanência ou pessoa suspeita' },
  { id: 'inativity', label: 'Inatividade (dormindo ou celular)' },
  { id: 'vehicle_detection', label: 'Detecção de veículo' },
  { id: 'vehicle_agglomeration', label: 'Congestionamento de veículos' },
  { id: 'animal_detection', label: 'Detecção de PET' },
  { id: 'facial_panic', label: 'Pânico facial' },
  { id: 'lpr', label: 'LPR - placa de veículos' },
  { id: 'radar', label: 'Radar de velocidade' },
  { id: 'face_recognition', label: 'Reconhecimento facial' },
  { id: 'epi_detection', label: 'Detecção de EPI' },
  { id: 'epi_ausence', label: 'Ausência de EPI' },
  { id: 'scene_change', label: 'Mudança de cena' },
  { id: 'timelapse', label: 'Timelapse' },
];