services:
  db:
    image: postgres:15-alpine
    container_name: nextjs_postgres
    restart: always
    environment:
      POSTGRES_USER: zions
      POSTGRES_PASSWORD: zions123
      POSTGRES_DB: leads_zions_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password (you can change it)
    ports:
      - "3020:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring


volumes:
  postgres_data:
  grafana_data:

networks:
  monitoring: 
    driver: bridge