export const env = {
    heimdallSubdomain: process.env.NEXT_PUBLIC_HEIMDALL_SUBDOMAIN || "",
    superadminUser: process.env.NEXT_PUBLIC_SUPERADMIN_USER || "",
    superadminPassword: process.env.NEXT_PUBLIC_SUPERADMIN_PASSWORD || "",
    commandToken: process.env.NEXT_PUBLIC_COMMAND_TOKEN || "",
    commandUrl: process.env.NEXT_PUBLIC_COMMAND_URL || "",
    columnId: process.env.NEXT_PUBLIC_COLUMN_ID || "",
    commandTokenAbrint: process.env.NEXT_PUBLIC_COMMAND_TOKEN_ABRINT || "",
    commandUrlAbrint: process.env.NEXT_PUBLIC_COMMAND_URL_ABRINT || "",
    columnIdAbrint: process.env.NEXT_PUBLIC_COLUMN_ID_ABRINT || "",
    mailMailer: process.env.MAIL_MAILER || "",
    mailHost: process.env.MAIL_HOST || "",
    mailPort: process.env.MAIL_PORT || "",
    mailUsername: process.env.MAIL_USERNAME || "",
    mailPassword: process.env.MAIL_PASSWORD || "",
    mailFromAddress: "smtp@zionstech.com.br",
    mailFromName: "Zions Vision",
    mailToken: process.env.MAIL_TOKEN || "",
    mailEncription: process.env.MAIL_ENCRYPTION || "",
};